services:
  fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    volumes:
      - .:/app  # 将当前目录挂载到容器的/app目录

      # 避免node_modules重复安装
      - ./data/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development  # 设置环境变量
      # - PORT=3100
